### ISSUE TITLE
Great extension!

### ISSUE THREAD

**Issue by johnyradio** [Venryx/extension-disabler#1]
awesome extension. How come missing from chrome web store? Google didn't like it?

many thx for making this available. MUCH NEEDED.

**Comment by Venryx** [comment]
Well, the extension is based on the one you saw on the ghacks website, and I just worked on it enough to get it working again. I'd only want to submit it to the webstore if I felt I'd gotten it "polished" more. (which isn't a priority for me at the moment)

Thanks for the comments though!

**Comment by johnyradio** [comment]
Seems ready for prime time to me :)

I applaud your perfectionism, but it's already fantastic. Not sure what you mean by "polish", but it looks and works great!

I think many people would be very grateful for this extension, as long as it doesn't have any bugs.  

Cheers!

**Comment by mrmckeb** [comment]
Looks great, I agree that it'd be good to launch this ASAP ;)
