### ISSUE TITLE
Clicking "View Settings" in popup causes "File_Not_Found_Error"

### ISSUE THREAD

**Issue by pritster5** [Venryx/extension-disabler#2]
In Popup.html, it seems that the "View Settings" link causes a "ERR_FILE_NOT_FOUND" to be thrown.
This is due to the following error: 

> Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by pritster5** [comment]
Ok so this bug is easier to fix then I thought. It just means we aren't allowed to use ANY inline js in our .html files. So we have to follow this syntax instead: 
`<script src="somescript.js"></script>`
Then we simply paste the code that we inlined into a seperate js file that is called in the above code (e.g. somescript.js)

The below document contains all the information needed to upgrade the extension to the latest (Manifest v2) standards
https://developer.chrome.com/extensions/tut_migration_to_manifest_v2#inline_scripts

**Comment by Venryx** [comment]
Okay; thanks for the info and pull-requests.

I will review them in the next few days, then update the repo with the improvements.

**Comment by Venryx** [comment]
The pull requests have been merged. Thanks for the help.
